Update test2.yml

diff --git a/.github/workflows/test2.yml b/.github/workflows/test2.yml
--- a/.github/workflows/test2.yml
+++ b/.github/workflows/test2.yml
@@ -20,4 +20,11 @@ jobs:
 
     - name: Run Test1
       run: |
-        output=$(node dist/Test1.js
+        output=$(node dist/Test1.js)
+        # capture exit code
+        exit_code=$output
+
+        if [$exit_code -ne 0]; then
+          echo "Error test fail $exit_code"
+          exit 1 #Exit the workflow because error
+        fi
