Update test2.yml

diff --git a/.github/workflows/test2.yml b/.github/workflows/test2.yml
--- a/.github/workflows/test2.yml
+++ b/.github/workflows/test2.yml
@@ -20,11 +20,10 @@ jobs:
 
     - name: Run Test1
       run: |
-        output=$(node dist/Test1.js)
-        # capture exit code
-        exit_code=$output
+        node dist/Test1.js
+        exit_code=$?
 
-        if [$exit_code -ne 0]; then
-          echo "Error test fail $exit_code"
-          exit 1 #Exit the workflow because error
+        if [ $exit_code -ne 0 ]; then
+          echo "Error test fail with exit code $exit_code"
+          exit 1
         fi
