Update test2.yml

diff --git a/.github/workflows/test2.yml b/.github/workflows/test2.yml
--- a/.github/workflows/test2.yml
+++ b/.github/workflows/test2.yml
@@ -1,10 +1,9 @@
 name: test2
 
 on:
-  push: 
-    branches: 
+  push:
+    branches:
       - main
-
 jobs:
   job1:
     runs-on: ubuntu-latest
@@ -17,13 +16,13 @@ jobs:
       uses: actions/setup-node@v2
       with:
         node-version: '14'
-
-    - name: Run Test1
+    - name: Run Test
       run: |
-        node dist/Test1.js
-        exit_code=$?
+        output=$(node dist/Test1.js)
+        # capture exit code
+        exit_code=$output
 
         if [ $exit_code -ne 0 ]; then
-          echo "Error test fail with exit code $exit_code"
-          exit 1
+          echo "Error test fail $exit_code"
+          exit 1 #Exit the workflow because error
         fi
